### ISSUE TITLE
Not working, lot of errors thrown while building the program 

### ISSUE THREAD

**Issue by dexbotdev** [0xpapercut/raydium-substream#1]
pb:Raydium_Events Not found
also there are 10-20 other issues thrown as error

**Comment by 0xpapercut** [comment]
Yes indeed at some point in time I made some changes to this repo, so maybe I broke something. My intention was to mix spltoken events with raydium but I dropped that idea, and so must revert back the proto changes. I will do that as soon as possible.

**Comment by 0xpapercut** [comment]
It works now. Note that only swap transactions are parsed, so if you want to capture initialize/deposite/withdraw, you will have to code it out. Let me know if I can close this.
