### ISSUE TITLE
this repo gives build errors

### ISSUE THREAD

**Issue by nabeel99** [0xpapercut/raydium-substream#3]
apparently the spl token substream , parse transfer functions expect 4 arguments but only 2 are passed ?, could you either update cargo lock with the correct version or update the current code ?

**Comment by 0xpapercut** [comment]
Yes indeed, I'm sorry im gonna fix it.

**Comment by 0xpapercut** [comment]
Should be fixed now.

**Comment by nabeel99** [comment]
@0xpapercut  what was the fix ? was the issue in the spl token substream repo ?
